version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21.3.0-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=verYs3cret
      - APP_USER=appuser
      - APP_USER_PASSWORD=password
      - ORACLE_DATABASE=user_authentication
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./sql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -L appuser/password@oracle-db:1521/user_authentication"]
      interval: 10s
      timeout: 10s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app-service:
    build: .
    container_name: user-authentication-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/user_authentication
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # Enable automatic schema creation
      - SPRING_FLYWAY_ENABLED=false  # Disable Flyway
      - SPRING_REDIS_HOST=redis
      - SPRING_MAIL_HOST=mailhog
    depends_on:
      oracle-db:
        condition: service_healthy
      redis:
        condition: service_started
      mailhog:
        condition: service_started

volumes:
  oracle-data:
